image: cirrusci/flutter:stable

stages:
  - upgrade_sdk
  - format
  - test
  - build

upgrade_sdk:
  stage: upgrade_sdk
  script:
    - flutter channel stable
    - flutter upgrade

format:
  stage: format
  script:
    - flutter analyze lib/ test/

test:
  stage: test
  script:
    - flutter test test/

build:
  stage: build
  script:
    - flutter build appbundle
    - flutter build apk
